"""
news_scraper.py: NewsAgent for silver market news extraction.
Scrapes news websites and uses OpenAI for structured data extraction.
"""

import asyncio
import random
import json
from datetime import datetime
from typing import List, Dict, Optional

from pydantic import BaseModel, Field
from playwright.async_api import async_playwright, Page
from mistralai import Mistral

from .db_helper import ScraperDBHelper


# -------------------------------------------------------------------
# 1. STRUCTURED OUTPUT SCHEMA
# -------------------------------------------------------------------
class SilverNewsArticle(BaseModel):
    title: str = Field(description="A concise, high-impact headline.")
    content: str = Field(description="20-word maximum summary of the article.")
    fetched_at: str = Field(description="ISO format timestamp generated by the agent.")
    source_url: str = Field(description="The full URL of the specific article.")
    raw_data: Dict = Field(description="Metadata: body_content (full article text), alt_text (image descriptions), tags (keywords).")


# -------------------------------------------------------------------
# 2. NEWS AGENT
# -------------------------------------------------------------------
class NewsAgent:
    def __init__(self, MISTRAL_API_KEY: str, db_helper: ScraperDBHelper):
        self.client = Mistral(api_key=MISTRAL_API_KEY)
        self.model = "mistral-small-latest"  # Fast and free tier friendly
        self.db_helper = db_helper

        self.sources = {
            "silverseek": {"url": "https://silverseek.com/articles/silver-market-updates"},
            "cnbc": {"url": "https://www.cnbc.com/quotes/XAG=?tab=news"},
            "yahoo": {"url": "https://finance.yahoo.com/quote/SI%3DF/news/"},
            "investing": {"url": "https://in.investing.com/commodities/silver-opinion"},
        }

    # -------------------------------------------------------------------
    # 3. STRUCTURED ARTICLE GENERATION (OPENAI)
    # -------------------------------------------------------------------
    async def generate_structured_article(self, title: str, content: str, url: str) -> Optional[Dict]:
        """
        Generate structured article data from scraped title and content.
        
        Args:
            title: Article title
            content: Article content (can be partial)
            url: Source URL
            
        Returns:
            Structured article dict or None if extraction fails
        """
        try:
            prompt = f"""
You are a Senior Commodity Analyst specializing in silver markets.
Analyze this silver market article and extract structured data.

RULES:
1. title: Keep it concise and professional (max 100 characters)
2. content: Create a 20-word MAXIMUM summary capturing the key insight
3. raw_data must include:
   - body_content: Full article text (all available content)
   - alt_text: Any image descriptions or captions found
   - tags: List of relevant keywords (e.g., ["silver", "price", "market", "forecast"])

Return ONLY valid JSON in this EXACT format (no markdown, no code blocks, no explanations):
{{
  "title": "",
  "content": "",
  "fetched_at": "{datetime.utcnow().isoformat()}",
  "source_url": "{url}",
  "raw_data": {{
    "body_content": "",
    "alt_text": "",
    "tags": []
  }}
}}

ARTICLE TITLE: {title}

ARTICLE CONTENT: {content[:4000]}
"""

            response = self.client.chat.complete(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                max_tokens=1000
            )
            content_text = response.choices[0].message.content.strip()
            
            # Remove markdown code blocks if present
            if content_text.startswith("```"):
                content_text = content_text.split("```")[1]
                if content_text.startswith("json"):
                    content_text = content_text[4:]
                content_text = content_text.strip()
            
            parsed = json.loads(content_text)
            article = SilverNewsArticle(**parsed)
            
            return article.model_dump()

        except Exception as e:
            print(f"[NewsAgent] Mistral Extraction Error: {e}")
            # Return a basic structure if AI fails
            # Create 20-word summary from content
            words = content.split()[:20] if content else ["Content", "extraction", "failed"]
            summary = " ".join(words)
            
            return {
                "title": title[:100] if title else "Silver Market Update",
                "content": summary,
                "fetched_at": datetime.utcnow().isoformat(),
                "source_url": url,
                "raw_data": {
                    "body_content": content[:5000] if content else "",
                    "alt_text": "",
                    "tags": ["silver", "market"]
                }
            }

    # -------------------------------------------------------------------
    # 4. CONTROLLER ENTRY POINT
    # -------------------------------------------------------------------
    async def execute_from_controller(self):
        target = self.db_helper.get_next_news_target()
        if not target:
            print("[NewsAgent] No targets found.")
            return {"success": False}

        source_name = target["source_name"]
        print(f"[NewsAgent] Controller assigned: {source_name}")

        articles, noise_data = await self.scrape_source(source_name)

        if articles:
            self.db_helper.insert_news_data(articles)
            print(f"[NewsAgent] Stored {len(articles)} articles.")

        self.db_helper.insert_noise_metrics("news", source_name, noise_data)
        self.db_helper.mark_target_completed(target["id"])

        return {"success": len(articles) > 0, "articles": len(articles)}

    # -------------------------------------------------------------------
    # 5. SCRAPING LOGIC
    # -------------------------------------------------------------------
    async def scrape_source(self, source_name: str) -> tuple[List[Dict], Dict]:
        """
        Scrape news from a specific source.
        
        Returns:
            (articles_list, noise_metrics_dict)
        """
        articles = []
        noise_count = 0

        async with async_playwright() as p:
            # Launch with stealth settings
            browser = await p.chromium.launch(
                headless=False,
                args=[
                    '--disable-blink-features=AutomationControlled',
                    '--disable-dev-shm-usage',
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                    '--disable-web-security',
                    '--disable-features=IsolateOrigins,site-per-process',
                ]
            )
            
            # Create context with realistic fingerprint
            context = await browser.new_context(
                viewport={"width": 1920, "height": 1080},
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                locale="en-US",
                timezone_id="America/New_York",
                permissions=["geolocation"],
                geolocation={"latitude": 40.7128, "longitude": -74.0060},  # New York
                color_scheme="light",
                extra_http_headers={
                    "Accept-Language": "en-US,en;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                    "DNT": "1",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1"
                }
            )
            
            page = await context.new_page()
            
            # Inject anti-detection scripts
            await page.add_init_script("""
                // Override the navigator.webdriver property
                Object.defineProperty(navigator, 'webdriver', {
                    get: () => undefined
                });
                
                // Mock plugins
                Object.defineProperty(navigator, 'plugins', {
                    get: () => [1, 2, 3, 4, 5]
                });
                
                // Mock languages
                Object.defineProperty(navigator, 'languages', {
                    get: () => ['en-US', 'en']
                });
                
                // Chrome runtime
                window.chrome = {
                    runtime: {}
                };
                
                // Permissions
                const originalQuery = window.navigator.permissions.query;
                window.navigator.permissions.query = (parameters) => (
                    parameters.name === 'notifications' ?
                        Promise.resolve({ state: Notification.permission }) :
                        originalQuery(parameters)
                );
            """)

            base_url = self.sources[source_name]["url"]
            print(f"[NewsAgent] Navigating to {base_url}")
            
            try:
                await page.goto(base_url, wait_until="domcontentloaded", timeout=30000)
                await self.human_like_behavior(page)
                await asyncio.sleep(2)  # Let page fully load

                # Try multiple selectors for different sites
                selectors = [
                    "article",
                    ".article",
                    ".Card",
                    "li.stream-item",
                    ".article-item",
                    "[class*='article']",
                    "[class*='story']",
                    "[class*='news']"
                ]
                
                blocks = []
                for selector in selectors:
                    blocks = await page.query_selector_all(selector)
                    if blocks:
                        print(f"[NewsAgent] Found {len(blocks)} items with selector: {selector}")
                        break
                
                if not blocks:
                    print("[NewsAgent] No article blocks found with any selector")
                    await browser.close()
                    return [], {"noise_ratio": 1.0, "total_blocks": 0}

                # Process first 5 blocks
                for idx, block in enumerate(blocks[:5]):
                    try:
                        text = await block.inner_text()
                        
                        # Look for links
                        link_elem = await block.query_selector("a")
                        href = await link_elem.get_attribute("href") if link_elem else None
                        
                        # Construct full URL
                        if href:
                            if href.startswith("http"):
                                full_url = href
                            elif href.startswith("/"):
                                from urllib.parse import urlparse
                                parsed = urlparse(base_url)
                                full_url = f"{parsed.scheme}://{parsed.netloc}{href}"
                            else:
                                full_url = base_url
                        else:
                            full_url = base_url

                        # Check if silver-related
                        text_lower = text.lower()
                        if "silver" in text_lower or "xag" in text_lower or "precious metal" in text_lower:
                            print(f"[NewsAgent] Processing article {idx + 1}: {text[:100]}...")
                            
                            # Extract title (first line usually)
                            lines = [line.strip() for line in text.split('\n') if line.strip()]
                            title = lines[0] if lines else "Silver Market Update"
                            content = ' '.join(lines[1:5]) if len(lines) > 1 else text[:500]
                            
                            # Generate structured article
                            data = await self.generate_structured_article(title, content, full_url)
                            if data:
                                articles.append(data)
                                print(f"[NewsAgent] ✅ Article extracted: {data['title'][:80]}")
                            else:
                                noise_count += 1
                        else:
                            noise_count += 1
                            
                    except Exception as e:
                        print(f"[NewsAgent] Error processing block {idx}: {e}")
                        noise_count += 1

            except Exception as e:
                print(f"[NewsAgent] Error during scraping: {e}")
            finally:
                await browser.close()

        total_blocks = len(blocks) if blocks else 1
        noise_metrics = {
            "noise_ratio": noise_count / max(total_blocks, 1),
            "total_blocks": total_blocks,
            "articles_extracted": len(articles),
            "noise_items": noise_count
        }

        return articles, noise_metrics

    # -------------------------------------------------------------------
    # 6. HUMAN-LIKE BROWSER BEHAVIOR
    # -------------------------------------------------------------------
    async def human_like_behavior(self, page: Page):
        """Simulate realistic human-like mouse movements and scrolling."""
        viewport = page.viewport_size
        
        if viewport:
            # Multiple random mouse movements
            for _ in range(random.randint(2, 4)):
                start = (random.randint(100, viewport["width"] - 100), 
                        random.randint(100, viewport["height"] - 100))
                end = (random.randint(100, viewport["width"] - 100), 
                      random.randint(100, viewport["height"] - 100))
                
                points = self.generate_bezier_curve(start, end)
                
                for x, y in points:
                    await page.mouse.move(x, y)
                    await asyncio.sleep(random.uniform(0.005, 0.015))
                
                # Random pause
                await asyncio.sleep(random.uniform(0.3, 0.8))
        
        # Realistic scrolling pattern
        scroll_patterns = [
            # Quick scroll down
            lambda: random.randint(300, 500),
            # Slow scroll down
            lambda: random.randint(100, 250),
            # Scroll up a bit (reading back)
            lambda: -random.randint(50, 150),
        ]
        
        for _ in range(random.randint(2, 4)):
            scroll_amount = random.choice(scroll_patterns)()
            await page.evaluate(f"window.scrollBy(0, {scroll_amount})")
            await asyncio.sleep(random.uniform(0.5, 1.5))
        
        # Final pause to "read"
        await asyncio.sleep(random.uniform(1.5, 3.0))

    def generate_bezier_curve(self, start, end, steps=100):
        """
        Generate cubic bezier curve points for natural mouse movement.
        Uses control points to create a more realistic curved path.
        """
        # Generate random control points for cubic bezier
        control1 = (
            start[0] + random.randint(-200, 200),
            start[1] + random.randint(-200, 200)
        )
        control2 = (
            end[0] + random.randint(-200, 200),
            end[1] + random.randint(-200, 200)
        )
        
        points = []
        for i in range(steps + 1):
            t = i / steps
            # Cubic bezier formula
            x = (1-t)**3 * start[0] + 3*(1-t)**2*t * control1[0] + 3*(1-t)*t**2 * control2[0] + t**3 * end[0]
            y = (1-t)**3 * start[1] + 3*(1-t)**2*t * control1[1] + 3*(1-t)*t**2 * control2[1] + t**3 * end[1]
            points.append((int(x), int(y)))
        
        return points
