"""
news_scraper.py: NewsAgent for silver market news extraction.
Scrapes news websites and uses OpenAI for structured data extraction.
"""

import asyncio
import random
import json
from datetime import datetime
from typing import List, Dict, Optional

from pydantic import BaseModel, Field
from playwright.async_api import async_playwright, Page
from mistralai import Mistral

from .db_helper import ScraperDBHelper


# -------------------------------------------------------------------
# 1. STRUCTURED OUTPUT SCHEMA
# -------------------------------------------------------------------
class SilverNewsArticle(BaseModel):
    title: str = Field(description="A concise, high-impact headline.")
    content: str = Field(description="20-word maximum summary of the article.")
    fetched_at: str = Field(description="ISO format timestamp generated by the agent.")
    source_url: str = Field(description="The full URL of the specific article.")
    raw_data: Dict = Field(description="Metadata: body_content (full article text), alt_text (image descriptions), tags (keywords).")


# -------------------------------------------------------------------
# 2. NEWS AGENT
# -------------------------------------------------------------------
class NewsAgent:
    def __init__(self, MISTRAL_API_KEY: str, db_helper: ScraperDBHelper):
        self.client = Mistral(api_key=MISTRAL_API_KEY)
        self.model = "mistral-small-latest"  # Fast and free tier friendly
        self.db_helper = db_helper

        self.sources = {
            "silverseek": {"url": "https://silverseek.com/articles/silver-market-updates"},
            "cnbc": {"url": "https://www.cnbc.com/quotes/XAG=?tab=news"},
            "yahoo": {"url": "https://finance.yahoo.com/quote/SI%3DF/news/"},
            "investing": {"url": "https://in.investing.com/commodities/silver-opinion"},
        }

    # -------------------------------------------------------------------
    # 3. STRUCTURED ARTICLE GENERATION (OPENAI)
    # -------------------------------------------------------------------
    async def generate_structured_article(self, title: str, content: str, url: str) -> Optional[Dict]:
        """
        Generate structured article data from scraped title and content.
        
        Args:
            title: Article title
            content: Article content (can be partial)
            url: Source URL
            
        Returns:
            Structured article dict or None if extraction fails
        """
        try:
            prompt = f"""
You are a Senior Commodity Analyst specializing in silver markets.
Analyze this silver market article and extract structured data.

RULES:
1. title: Keep it concise and professional (max 100 characters)
2. content: Create a 20-word MAXIMUM summary capturing the key insight
3. raw_data must include:
   - body_content: Full article text (all available content)
   - alt_text: Any image descriptions or captions found
   - tags: List of relevant keywords (e.g., ["silver", "price", "market", "forecast"])

Return ONLY valid JSON in this EXACT format (no markdown, no code blocks, no explanations):
{{
  "title": "",
  "content": "",
  "fetched_at": "{datetime.utcnow().isoformat()}",
  "source_url": "{url}",
  "raw_data": {{
    "body_content": "",
    "alt_text": "",
    "tags": []
  }}
}}

ARTICLE TITLE: {title}

ARTICLE CONTENT: {content[:4000]}
"""

            response = self.client.chat.complete(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                max_tokens=1000
            )
            content_text = response.choices[0].message.content.strip()
            
            # Remove markdown code blocks if present
            if content_text.startswith("```"):
                content_text = content_text.split("```")[1]
                if content_text.startswith("json"):
                    content_text = content_text[4:]
                content_text = content_text.strip()
            
            parsed = json.loads(content_text)
            article = SilverNewsArticle(**parsed)
            
            return article.model_dump()

        except Exception as e:
            print(f"[NewsAgent] Mistral Extraction Error: {e}")
            # Return a basic structure if AI fails
            # Create 20-word summary from content
            words = content.split()[:20] if content else ["Content", "extraction", "failed"]
            summary = " ".join(words)
            
            return {
                "title": title[:100] if title else "Silver Market Update",
                "content": summary,
                "fetched_at": datetime.utcnow().isoformat(),
                "source_url": url,
                "raw_data": {
                    "body_content": content[:5000] if content else "",
                    "alt_text": "",
                    "tags": ["silver", "market"]
                }
            }

    # -------------------------------------------------------------------
    # 4. CONTROLLER ENTRY POINT
    # -------------------------------------------------------------------
    async def execute_from_controller(self):
        target = self.db_helper.get_next_news_target()
        if not target:
            print("[NewsAgent] No targets found.")
            return {"success": False, "articles": 0}

        source_name = target["name"]
        source_url = target.get("url")
        target_id = target.get("id")
        print(f"[NewsAgent] Controller assigned: {source_name} ({source_url})")

        if not source_url:
            print(f"[NewsAgent] Error: No URL found for target {source_name}")
            return {"success": False, "error": "Missing URL", "articles": 0}

        try:
            articles, noise_data = await self.scrape_source(source_name, source_url)

            if articles:
                inserted = self.db_helper.insert_news_data(articles, target_id=target_id)
                print(f"[NewsAgent] Stored {len(articles)} articles. DB insert: {inserted}")

            self.db_helper.insert_noise_metrics("news", source_name, noise_data)
            self.db_helper.mark_target_completed(target_id)

            return {"success": len(articles) > 0, "articles": len(articles)}
        except Exception as e:
            print(f"[NewsAgent] Controller execution error: {type(e).__name__}: {e}")
            import traceback
            traceback.print_exc()
            return {"success": False, "error": str(e), "articles": 0}

    # -------------------------------------------------------------------
    # 5. SCRAPING LOGIC
    # -------------------------------------------------------------------
    async def scrape_source(self, source_name: str, base_url: str) -> tuple[List[Dict], Dict]:
        """
        Scrape news from a specific source URL.
        Simplified version - just gets first/latest articles.
        
        Returns:
            (articles_list, noise_metrics_dict)
        """
        articles = []
        noise_count = 0
        blocks = []
        
        print(f"[NewsAgent] Scraping {source_name}: {base_url}")

        async with async_playwright() as p:
            try:
                # Launch with minimal settings for speed
                browser = await p.chromium.launch(headless=True)
                
                page = await browser.new_page()
                
                # Set timeout to 15 seconds instead of 30 - fail fast
                page.set_default_timeout(15000)
                page.set_default_navigation_timeout(15000)
                
                print(f"[NewsAgent] Navigating to {base_url}...")
                
                # Try to load the page - if it fails, we skip this source
                try:
                    await page.goto(base_url, wait_until="load", timeout=15000)
                except Exception as e:
                    print(f"[NewsAgent] ⚠️  Navigation timeout/failed for {source_name}: {e}")
                    print(f"[NewsAgent] Will try to scrape whatever loaded...")
                
                # Short wait for any dynamic content
                await asyncio.sleep(1)
                
                # Simple approach: Get all visible text content grouped by headers/paragraphs
                # This is more reliable than trying specific selectors
                
                print(f"[NewsAgent] Extracting content from page...")
                
                # Get all headers and their following content
                try:
                    # Method 1: Try to get article elements first
                    all_articles = await page.query_selector_all("article, [role='article'], .article, .news-item, .post")
                    
                    if all_articles:
                        print(f"[NewsAgent] Found {len(all_articles)} article elements")
                        blocks = all_articles[:5]  # Take first 5
                    else:
                        # Method 2: Fallback to headers which usually have article titles
                        headers = await page.query_selector_all("h1, h2, h3, h4, h5")
                        
                        if headers:
                            print(f"[NewsAgent] Found {len(headers)} headers, using as article titles")
                            blocks = headers[:5]  # Take first 5 headers
                        else:
                            # Method 3: Last resort - get all divs that contain text
                            divs = await page.query_selector_all("div[class*='item'], div[class*='article'], div[class*='post'], li")
                            if divs:
                                print(f"[NewsAgent] Found {len(divs)} potential article divs")
                                blocks = divs[:5]
                            else:
                                print("[NewsAgent] ❌ No content found on page")
                                await browser.close()
                                return [], {"noise_ratio": 1.0, "total_blocks": 0, "articles_extracted": 0, "noise_items": 0}
                    
                    print(f"[NewsAgent] Processing {len(blocks)} content blocks...")
                    
                    # Process each block
                    for idx, block in enumerate(blocks):
                        try:
                            # Get text and any links
                            text = await block.inner_text()
                            text = text.strip()
                            
                            if not text or len(text) < 10:
                                noise_count += 1
                                continue
                            
                            # Try to find a link in this block
                            link_elem = await block.query_selector("a")
                            href = None
                            if link_elem:
                                href = await link_elem.get_attribute("href")
                            
                            # Construct full URL
                            if href:
                                if href.startswith("http"):
                                    full_url = href
                                elif href.startswith("/"):
                                    from urllib.parse import urlparse
                                    parsed = urlparse(base_url)
                                    full_url = f"{parsed.scheme}://{parsed.netloc}{href}"
                                else:
                                    full_url = base_url
                            else:
                                full_url = base_url
                            
                            # Extract title and content
                            lines = [line.strip() for line in text.split('\n') if line.strip()]
                            
                            if not lines:
                                noise_count += 1
                                continue
                            
                            title = lines[0][:100]
                            content = ' '.join(lines[1:3]) if len(lines) > 1 else lines[0][:200]
                            
                            print(f"[NewsAgent] Article {idx + 1}: {title[:60]}...")
                            
                            # Try to generate structured article using LLM
                            try:
                                data = await self.generate_structured_article(title, content, full_url)
                                if data:
                                    articles.append(data)
                                    print(f"[NewsAgent] ✅ Extracted: {data['title'][:60]}...")
                                else:
                                    noise_count += 1
                            except Exception as e:
                                # If LLM fails, create basic article manually
                                print(f"[NewsAgent] LLM extraction failed ({e}), using manual extraction...")
                                manual_article = {
                                    "title": title,
                                    "content": content[:200],
                                    "fetched_at": datetime.utcnow().isoformat(),
                                    "source_url": full_url,
                                    "raw_data": {
                                        "body_content": text[:1000],
                                        "alt_text": "",
                                        "tags": ["silver", "market", "news"]
                                    }
                                }
                                articles.append(manual_article)
                                print(f"[NewsAgent] ✅ Manual extraction: {title[:60]}...")
                                
                        except Exception as e:
                            print(f"[NewsAgent] Error processing block {idx}: {type(e).__name__}: {e}")
                            noise_count += 1
                            continue
                    
                    print(f"[NewsAgent] Extracted {len(articles)} articles successfully")
                    
                except Exception as e:
                    print(f"[NewsAgent] Error during content extraction: {type(e).__name__}: {e}")
                    import traceback
                    traceback.print_exc()
                
                await browser.close()
                
            except Exception as e:
                print(f"[NewsAgent] Unexpected error: {type(e).__name__}: {e}")
                import traceback
                traceback.print_exc()
                try:
                    await browser.close()
                except:
                    pass

        total_blocks = len(blocks) if blocks else 1
        noise_metrics = {
            "noise_ratio": noise_count / max(total_blocks, 1),
            "total_blocks": total_blocks,
            "articles_extracted": len(articles),
            "noise_items": noise_count
        }

        return articles, noise_metrics

    # -------------------------------------------------------------------
    # 6. HUMAN-LIKE BROWSER BEHAVIOR
    # -------------------------------------------------------------------
    async def human_like_behavior(self, page: Page):
        """Simulate realistic human-like mouse movements and scrolling."""
        viewport = page.viewport_size
        
        if viewport:
            # Multiple random mouse movements
            for _ in range(random.randint(2, 4)):
                start = (random.randint(100, viewport["width"] - 100), 
                        random.randint(100, viewport["height"] - 100))
                end = (random.randint(100, viewport["width"] - 100), 
                      random.randint(100, viewport["height"] - 100))
                
                points = self.generate_bezier_curve(start, end)
                
                for x, y in points:
                    await page.mouse.move(x, y)
                    await asyncio.sleep(random.uniform(0.005, 0.015))
                
                # Random pause
                await asyncio.sleep(random.uniform(0.3, 0.8))
        
        # Realistic scrolling pattern
        scroll_patterns = [
            # Quick scroll down
            lambda: random.randint(300, 500),
            # Slow scroll down
            lambda: random.randint(100, 250),
            # Scroll up a bit (reading back)
            lambda: -random.randint(50, 150),
        ]
        
        for _ in range(random.randint(2, 4)):
            scroll_amount = random.choice(scroll_patterns)()
            await page.evaluate(f"window.scrollBy(0, {scroll_amount})")
            await asyncio.sleep(random.uniform(0.5, 1.5))
        
        # Final pause to "read"
        await asyncio.sleep(random.uniform(1.5, 3.0))

    def generate_bezier_curve(self, start, end, steps=100):
        """
        Generate cubic bezier curve points for natural mouse movement.
        Uses control points to create a more realistic curved path.
        """
        # Generate random control points for cubic bezier
        control1 = (
            start[0] + random.randint(-200, 200),
            start[1] + random.randint(-200, 200)
        )
        control2 = (
            end[0] + random.randint(-200, 200),
            end[1] + random.randint(-200, 200)
        )
        
        points = []
        for i in range(steps + 1):
            t = i / steps
            # Cubic bezier formula
            x = (1-t)**3 * start[0] + 3*(1-t)**2*t * control1[0] + 3*(1-t)*t**2 * control2[0] + t**3 * end[0]
            y = (1-t)**3 * start[1] + 3*(1-t)**2*t * control1[1] + 3*(1-t)*t**2 * control2[1] + t**3 * end[1]
            points.append((int(x), int(y)))
        
        return points
